vich_uploader:
    db_driver: orm

    mappings:
        categories:
                    uri_prefix: /images/categories
                    upload_destination: '%kernel.project_dir%/public/images/categories'
                            
        produits:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
            
        carriers:
            uri_prefix: /images/carriers
            upload_destination: '%kernel.project_dir%/public/images/carriers'
                    
                
        headers:
            uri_prefix: /images/headers
            upload_destination: '%kernel.project_dir%/public/images/headers'
                    